global using LeaveManagement.Common.Static;
global using LeaveManagement.Data;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.UI.Services;
global using System.ComponentModel.DataAnnotations;
global using LeaveManagement.Application.Models.LeaveAllocations;
global using LeaveManagement.Application.Models.LeaveRequests;
global using LeaveManagement.Application.Models.LeaveTypes;
global using LeaveManagement.Application.Models.Periods;